#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexCrossword.HexRegex
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\HexRegex\HexRegexCrosswordHtml.cshtml"
    using HexRegex;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    internal partial class HexRegexCrosswordHtml : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 3 "..\..\HexRegex\HexRegexCrosswordHtml.cshtml"

    public HexRegexCrossword Model { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n<html>\r\n    <head>\r\n<!-- Hex grid based on http://stackoverflow.com/questions/1" +
"0062887/generate-repeating-hexagonal-pattern-with-css3 -->\r\n        <style type=" +
"\"text/css\">\r\n            \r\n            \r\nqq * { box-sizing: border-box; margin: " +
"0; padding: 0; }\r\n.hexrow { text-align: center; }\r\n/* .hexrow:first-child { marg" +
"in-top: 7%; } */\r\nqq .hexagon {\r\n    /* vert box is x wide, sqrt(3)*x tall */\r\n " +
"   width: 2em;\r\n    height: 3.46em;\r\n    position: relative;\r\n    display: inlin" +
"e-block;\r\n    overflow: hidden;\r\n    margin: 0 8.5%;\r\n    padding: 16%;\r\n/*    t" +
"ransform: rotate(30deg) skewY(30deg) scaleX(.866); /* .866 = sqrt(3)/2 = sin(60 " +
"deg) */\r\n    background-color: green;\r\n}\r\nqq .hexagon:before {\r\n    display: blo" +
"ck;\r\n    position: absolute;\r\n    /* 86.6% = (sqrt(3)/2)*100% = .866*100% */\r\n  " +
"  top: 6.7%; right: 0; bottom: 6.7%; left: 0; /* 6.7% = (100% -86.6%)/2 */\r\n    " +
"transform: scaleX(1.155) /* 1.155 = 2/sqrt(3) */ \r\n               skewY(-30deg) " +
"rotate(-30deg);\r\n    background-color: yellow;\r\n    background-size: cover;\r\n   " +
" content: \'\';\r\n}\r\n\r\nqq .hexagon:after {\r\n    display: block;\r\n    position: abso" +
"lute;\r\n    /* 86.6% = (sqrt(3)/2)*100% = .866*100% */\r\n    top: 6.7%; right: 0; " +
"bottom: 6.7%; left: 0; /* 6.7% = (100% -86.6%)/2 */\r\n    transform: scaleX(1.155" +
") /* 1.155 = 2/sqrt(3) */ \r\n               skewY(-30deg) rotate(-30deg);\r\n    ba" +
"ckground-color: red;\r\n    background-size: cover;\r\n    content: \'\';\r\n}\r\n\r\n/*****" +
"***************/\r\n\r\n\r\n.hexagon {\r\n    border-color: black;\r\n    border-style: so" +
"lid;\r\n    border-width: 0 1px;\r\n    display: inline;\r\n    padding: 0.5em;\r\n}\r\n\r\n" +
"        </style>\r\n    </head>\r\n    <body>\r\n        <div id=\"grid\">\r\n");


            
            #line 66 "..\..\HexRegex\HexRegexCrosswordHtml.cshtml"
             for (int row = 0; row <= Model.GridRows.GetUpperBound(1); row++)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"hexrow\">\r\n                    <div class=\"clue\">");


            
            #line 69 "..\..\HexRegex\HexRegexCrosswordHtml.cshtml"
                                 Write(Model.Clues[0, row]);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 70 "..\..\HexRegex\HexRegexCrosswordHtml.cshtml"
                     foreach (var ch in Model.GridRows[0, row])
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div class=\"hexagon\">");


            
            #line 72 "..\..\HexRegex\HexRegexCrosswordHtml.cshtml"
                                        Write(ch);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 73 "..\..\HexRegex\HexRegexCrosswordHtml.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n");


            
            #line 75 "..\..\HexRegex\HexRegexCrosswordHtml.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
